---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaowu.
--- DateTime: 2022/8/20 16:32
---
local kUrl = KEYS[1];
local kHash = KEYS[2];
local expired = ARGV[1];
local hash = ARGV[2];
local longUrl = ARGV[3];
local startDate = ARGV[4];
local endDate = ARGV[5];
if expired ~= 0 then
    if redis.call("setex", kUrl, expired, hash) ~= false then
        if redis.call("hmset", kHash, "url", longUrl, "hash", hash, "start_date", startDate, "end_date", endDate) ~= false then
            return redis.call("expire", kHash, expired)
        end
    end
else
    --永不过期的地址
    if redis.call("set", kUrl, hash) ~= false then
        return redis.call("hmset", kHash, "url", longUrl, "hash", hash, "start_date", startDate, "end_date", endDate)
    end
end
return false